/**
 * Runtime Zod schema for VocalScore — closes T-009.
 *
 * Until this file existed, callers parsed score JSON with JSON.parse and
 * type-asserted to `VocalScore`. Malformed inputs (missing notes, non-numeric
 * startSec, NaN, Infinity, negative durations, MIDI out-of-range) silently
 * propagated into the synth engine, where they produced NaN audio or
 * out-of-bounds writes.
 *
 * The schema mirrors `src/types/score.ts` exactly. Field-level constraints
 * forbid NaN/Infinity on all numerics and enforce non-negative startSec /
 * positive durationSec / MIDI 0..127. Failure messages are intentionally
 * verbose so the calling CLI / server route can surface them to the user.
 *
 * TB-010: an optional `formatVersion` field + SUPPORTED_SCORE_VERSIONS gate
 * mirror the preset-loader's T-010 discipline so a v2 score generated by a
 * future tool fails loud on a v1 engine instead of silently dropping new
 * required fields via undefined-default.
 */
import { z } from 'zod';

// `z.number()` accepts NaN; the .finite() refinement is the only way to
// reject NaN and ±Infinity through Zod. Use it everywhere a number is parsed
// from JSON. (`z.number().finite()` is short enough we don't bother with a
// helper.)

const FiniteNumber = z.number().finite();

const VibratoSchema = z.object({
  rateHz: FiniteNumber.nonnegative(),
  depthCents: FiniteNumber.nonnegative(),
  onsetSec: FiniteNumber.nonnegative(),
});

const VocalNoteSchema = z.object({
  id: z.string().min(1),
  startSec: FiniteNumber.nonnegative(),
  durationSec: FiniteNumber.positive(),
  midi: FiniteNumber.min(0).max(127),
  velocity: FiniteNumber.min(0).max(1).optional(),
  timbre: z.string().min(1).optional(),
  vibrato: VibratoSchema.optional(),
  portamentoSec: FiniteNumber.nonnegative().optional(),
  // FE-004: per-voice stereo pan in [-1, 1]. Equal-power panning is applied
  // when the engine is configured for `channels: 2`; on mono renders the
  // field is accepted but ignored. Default at engine layer is 0 (center).
  pan: FiniteNumber.min(-1).max(1).optional(),
});

const PhonemeEventSchema = z.object({
  tSec: FiniteNumber.nonnegative(),
  durSec: FiniteNumber.positive(),
  phoneme: z.string().min(1),
  kind: z.enum(['vowel', 'consonant']),
  timbreHint: z.string().min(1).optional(),
  strength: FiniteNumber.min(0).max(1).optional(),
});

const AutomationPointSchema = z.object({
  tSec: FiniteNumber.nonnegative(),
  value: FiniteNumber,
});

const LyricsSchema = z.object({
  text: z.string(),
  language: z.string().min(1).optional(),
});

const LanesSchema = z.object({
  dynamics: z.array(AutomationPointSchema).optional(),
  breathiness: z.array(AutomationPointSchema).optional(),
  // timbreMorph maps timbre IDs to automation curves.
  timbreMorph: z.record(z.string(), z.array(AutomationPointSchema)).optional(),
});

// TB-010: strict semver regex for the score format version. Same shape as
// the preset-loader's gating in src/preset/schema.ts so the two version
// gates speak the same vocabulary. Optional at the field level for back-
// compat with pre-TB-010 scores (treated as '1.0.0').
const SCORE_FORMAT_VERSION_RE = /^\d+\.\d+\.\d+$/;
const SCORE_FORMAT_VERSION_DEFAULT = '1.0.0';

/**
 * Score format versions this engine understands. Keep aligned with
 * SCORE_FORMAT_VERSION_DEFAULT so unversioned-but-valid scores load
 * cleanly. When the schema grows new required fields (new lane types,
 * formant overrides), bump this list AND add a migration note in
 * CHANGELOG. Removing a version is a breaking change.
 */
export const SUPPORTED_SCORE_VERSIONS: readonly string[] = ['1.0.0'];

export const VocalScoreSchema = z.object({
  // TB-010: optional formatVersion mirrors preset version gating. Default
  // '1.0.0' preserves backward-compat — a score generated before this
  // field existed parses unchanged and the gate treats it as v1.0.0.
  formatVersion: z.string().regex(SCORE_FORMAT_VERSION_RE, {
    message: "formatVersion must be a strict semver MAJOR.MINOR.PATCH string (e.g. '1.0.0')",
  }).default(SCORE_FORMAT_VERSION_DEFAULT),
  bpm: FiniteNumber.positive(),
  notes: z.array(VocalNoteSchema),
  lyrics: LyricsSchema.optional(),
  phonemes: z.array(PhonemeEventSchema).optional(),
  lanes: LanesSchema.optional(),
});

export type VocalScoreParsed = z.infer<typeof VocalScoreSchema>;

/**
 * Parse + validate a score from raw JSON text. Throws a Zod validation error
 * with a list of field paths + reasons on invalid input. Use this in place of
 * `JSON.parse(content) as VocalScore` at trust boundaries.
 *
 * The thrown error keeps Zod's own message text (no rewrapping) so callers
 * can render either `err.message` (concise) or `err.issues` (structured).
 *
 * TB-010: after Zod parsing, an explicit version-compat gate rejects
 * formatVersion values outside SUPPORTED_SCORE_VERSIONS with
 * UNSUPPORTED_SCORE_VERSION so a v2 score on a v1 engine fails loud
 * rather than rendering with new fields undefined-defaulted.
 */
export function parseVocalScore(jsonText: string): VocalScoreParsed {
  const raw = JSON.parse(jsonText);
  const parsed = VocalScoreSchema.parse(raw);
  if (!SUPPORTED_SCORE_VERSIONS.includes(parsed.formatVersion)) {
    const err: any = new Error(
      `UNSUPPORTED_SCORE_VERSION: score formatVersion '${parsed.formatVersion}' is not supported by this build. ` +
      `Supported: [${SUPPORTED_SCORE_VERSIONS.join(', ')}].`
    );
    err.code = 'UNSUPPORTED_SCORE_VERSION';
    err.scoreVersion = parsed.formatVersion;
    err.supportedVersions = SUPPORTED_SCORE_VERSIONS;
    throw err;
  }
  return parsed;
}
